In [ ]:
from sklearn.datasets import load_iris

# 题目要求使用.csv文件，这里先将sklearn自带的iris数据集保存为CSV

In [ ]:
iris = load_iris()

In [ ]:
type(iris)

In [ ]:
iris.keys()

In [ ]:
iris.feature_names
type(iris.feature_names)

In [ ]:
iris.target

In [ ]:
iris.target_names

In [ ]:
import pandas as pd

In [ ]:
iris_data = pd.DataFrame(iris.data,columns=list(iris.feature_names))

In [ ]:
label = pd.DataFrame(iris.target,columns=['target'])

In [ ]:
label

In [ ]:
iris_data['target'] = label

In [ ]:
iris_data.head(5)

In [ ]:
iris_data.head(20)

In [ ]:
iris_data.to_csv('iris.csv')

# 使用XGBoost训练iris

In [ ]:
data = pd.read_csv("iris.csv")

In [ ]:
iris_types = data["target"].unique()#得到target列的类别数

In [ ]:
iris_types

In [ ]:
#如果csv中的类别没有表示为0,1,2..这种形式，那么需要转化为这种形式,如果已经为这种形式了，下面的代码也不会出错
for i,types in enumerate(iris_types):
    print(i,types)
    data.at[data["target"]==types,"target"] = i  #该段代码是将为某一类别的那些行的target的值置为该类别对应的序号

In [ ]:
# data.drop(columns=["Unnamed: 0"],axis=1,inplace=True)
data.head(5)

In [ ]:
import numpy as np
x, y = np.split(data.values, (4,), axis=1)#其中4代表保留前4列给x,剩余的给y

In [174]:
import sklearn
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import accuracy_score,roc_auc_score
from sklearn.preprocessing import OneHotEncoder

In [204]:
#将特征列数据归一化化
min_max_scaler = sklearn.preprocessing.MinMaxScaler(feature_range=(0,1))#归一到0-1之间
x = min_max_scaler.fit_transform(x)
#将目标类数据用one-hot表示
y = OneHotEncoder(sparse = False).fit_transform(y.reshape(-1,1))

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [176]:
#划分训练和测试集
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [177]:
from xgboost.sklearn import XGBClassifier #需要额外安装xgboost包，比如pip install xgboost
from sklearn.multiclass import OneVsRestClassifier

In [178]:
xgb = OneVsRestClassifier(XGBClassifier(),n_jobs=2)#XGBClassifier()对象不填参数就是默认参数，在fit的时候默认参数将被打印出来

In [179]:
xgb.fit(x_train,y_train)

OneVsRestClassifier(estimator=XGBClassifier(base_score=None, booster=None,
                                            colsample_bylevel=None,
                                            colsample_bynode=None,
                                            colsample_bytree=None, gamma=None,
                                            gpu_id=None, importance_type='gain',
                                            interaction_constraints=None,
                                            learning_rate=None,
                                            max_delta_step=None, max_depth=None,
                                            min_child_weight=None, missing=nan,
                                            monotone_constraints=None,
                                            n_estimators=100, n_jobs=None,
                                            num_parallel_tree=None,
                                            random_state=None, reg_alpha=None,
                                      

In [181]:
#预测
pre_result = xgb.predict(x_test)

In [ ]:
pre_result

In [182]:
#ROC曲线下面积
auc_score = roc_auc_score(y_test,pre_result)
pre_score = accuracy_score(y_test,pre_result)

In [185]:
auc_score

0.9675367077743987

In [187]:
pre_score

0.9555555555555556

# 堆叠n个dense层形成一个浅层的神经网络实现iris的多分类

In [123]:
import keras

In [124]:
iris_model = keras.models.Sequential()

In [127]:
#定义模型
init = keras.initializers.glorot_uniform(seed=1)#对应权重初始化参数
iris_model.add(keras.layers.Dense(units=5, input_dim=4, kernel_initializer=init, activation='relu'))
iris_model.add(keras.layers.Dense(units=6, kernel_initializer=init, activation='relu'))
iris_model.add(keras.layers.Dense(units=3, kernel_initializer=init, activation='softmax'))
iris_model.compile(loss='categorical_crossentropy', optimizer=keras.optimizers.Adam(), metrics=['accuracy'])

In [138]:
#训练。把训练集划分出一部分为验证集
history = iris_model.fit(x_train, y_train,validation_split=0.3,batch_size=20, epochs=20, shuffle=True, verbose=1)

Train on 73 samples, validate on 32 samples
Epoch 1/20
73/73 [==============================] - 0s 205us/step - loss: 0.4113 - accuracy: 0.9315 - val_loss: 0.3862 - val_accuracy: 0.9375
Epoch 2/20
73/73 [==============================] - 0s 178us/step - loss: 0.4089 - accuracy: 0.9315 - val_loss: 0.3857 - val_accuracy: 0.9375
Epoch 3/20
73/73 [==============================] - 0s 164us/step - loss: 0.4069 - accuracy: 0.9315 - val_loss: 0.3831 - val_accuracy: 0.9375
Epoch 4/20
73/73 [==============================] - 0s 233us/step - loss: 0.4032 - accuracy: 0.9315 - val_loss: 0.3800 - val_accuracy: 0.9375
Epoch 5/20
73/73 [==============================] - 0s 192us/step - loss: 0.4009 - accuracy: 0.9452 - val_loss: 0.3782 - val_accuracy: 0.9688
Epoch 6/20
73/73 [==============================] - 0s 288us/step - loss: 0.3970 - accuracy: 0.9452 - val_loss: 0.3758 - val_accuracy: 0.9375
Epoch 7/20
73/73 [==============================] - 0s 178us/step - loss: 0.3930 - accuracy: 0.9452 - va

In [141]:
#得到测试集上的损失和准确度
evaluation = iris_model.evaluate(x_test,y_test,verbose=1)

45/45 [==============================] - 0s 89us/step


In [142]:
evaluation

[0.3124969310230679, 1.0]

# 使用lightgbm训练iris

In [144]:
import lightgbm as lgbm

In [170]:
#训练参数
params={
    'learning_rate':0.1,
    'lambda_l1':0.1,
    'lambda_l2':0.2,
    'max_depth':4,
    'objective':'multiclass',
    'num_class':3,  #lightgbm.basic.LightGBMError: b‘Number of classes should be specified and greater than 1 for multiclass training‘
}

In [171]:
#lightgbm
lgb_train = lgbm.Dataset(x_train,y_train)
lgb_eval = lgbm.Dataset( x_test, y_test,reference=lgb_train)


In [172]:
lgbm_model = lgbm.train(params,lgb_train,num_boost_round=20,valid_sets=lgb_eval, early_stopping_rounds=5 )

[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000339 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 79
[LightGBM] [Info] Number of data points in the train set: 105, number of used features: 4
[LightGBM] [Info] Start training from score -1.188224
[LightGBM] [Info] Start training from score -0.965081
[LightGBM] [Info] Start training from score -1.157453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[1]	valid_0's multi_logloss: 0.964384
Training until validation scores don't improve for 5 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[2]

c:\anaconda3\envs\tf2.0\lib\site-packages\lightgbm\basic.py:154: UserWarning: Converting column-vector to 1d array
  _log_warning('Converting column-vector to 1d array')


In [214]:
lgbm_pre_result = list(lgbm_model.predict(x_test))#预测结果为每一个样本有三个概率值的形式